// js/config/GameConfig.js
const DEBUG_GRID = true;

const ENEMY_STATS = {
  slime: {
    hp: 30,
    damage: 5,
    speed: 40,
    detectionRange: 90,
    attackRange: 22,
    attackCooldown: 1400,
  },
  goblin: {
    hp: 60,
    damage: 10,
    speed: 55,
    detectionRange: 120,
    attackRange: 24,
    attackCooldown: 1200,
  },
  golem: {
    hp: 500,
    damage: 8,
    speed: 25,
    detectionRange: 110,
    attackRange: 30,
    attackCooldown: 1800,
  },
  lizardman1: {
    hp: 90,
    damage: 14,
    speed: 60,
    detectionRange: 130,
    attackRange: 26,
    attackCooldown: 1150,
  },
  lizardman2: {
    hp: 110,
    damage: 16,
    speed: 65,
    detectionRange: 135,
    attackRange: 26,
    attackCooldown: 1100,
  },
  lizardman3: {
    hp: 130,
    damage: 18,
    speed: 70,
    detectionRange: 140,
    attackRange: 28,
    attackCooldown: 1050,
  },
  skeleton1: {
    hp: 150,
    damage: 20,
    speed: 58,
    detectionRange: 140,
    attackRange: 28,
    attackCooldown: 1100,
  },
  skeleton2: {
    hp: 175,
    damage: 23,
    speed: 60,
    detectionRange: 145,
    attackRange: 28,
    attackCooldown: 1050,
  },
  skeleton3: {
    hp: 200,
    damage: 26,
    speed: 62,
    detectionRange: 150,
    attackRange: 30,
    attackCooldown: 1000,
  },
  demon1: {
    hp: 230,
    damage: 32,
    speed: 68,
    detectionRange: 155,
    attackRange: 30,
    attackCooldown: 950,
  },
  demon2: {
    hp: 260,
    damage: 36,
    speed: 72,
    detectionRange: 160,
    attackRange: 32,
    attackCooldown: 900,
  },
  demon3: {
    hp: 300,
    damage: 42,
    speed: 76,
    detectionRange: 170,
    attackRange: 34,
    attackCooldown: 850,
  },
};

const ENEMY_XP_REWARDS = {
  slime: 2,
  goblin: 4,
  golem: 8,
  lizardman1: 10,
  lizardman2: 12,
  lizardman3: 14,
  skeleton1: 16,
  skeleton2: 18,
  skeleton3: 20,
  demon1: 25,
  demon2: 30,
  demon3: 35,
};

const CONSUMABLES = {
  apple: { heal: 10, label: 'Apple' },
};

const HERO_LEVELS = {
  1: { xpToNext: 100, assetKey: 'hero_lvl1' },
  2: { xpToNext: 200, assetKey: 'hero_lvl2' },
  3: { xpToNext: 300, assetKey: 'hero_lvl3' },
  4: { xpToNext: 400, assetKey: 'hero_lvl4' },
  5: { xpToNext: 500, assetKey: 'hero_lvl5' },
  6: { xpToNext: 600, assetKey: 'hero_lvl6' },
  7: { xpToNext: 700, assetKey: 'hero_lvl7' },
  8: { xpToNext: 800, assetKey: 'hero_lvl8' },
  9: { xpToNext: null, assetKey: 'hero_lvl9' },
};

const HERO_STATS = {
  1: { maxHp: 100, attackDamage: 10 },
  2: { maxHp: 120, attackDamage: 14 },
  3: { maxHp: 140, attackDamage: 18 },
  4: { maxHp: 165, attackDamage: 23 },
  5: { maxHp: 190, attackDamage: 28 },
  6: { maxHp: 215, attackDamage: 34 },
  7: { maxHp: 240, attackDamage: 40 },
  8: { maxHp: 270, attackDamage: 47 },
  9: { maxHp: 300, attackDamage: 55 },
};

const HERO_ASSETS = {
  hero_lvl1: {
    basePath: 'assets/characters/swordsman/swordsman_level_1/',
    sheets: {
      idle:    { file: 'Swordsman_lvl1_Idle_with_shadow.png',        frames: 12 },
      walk:    { file: 'Swordsman_lvl1_Walk_with_shadow.png',        frames: 6  },
      run:     { file: 'Swordsman_lvl1_Run_with_shadow.png',         frames: 8  },
      attack:  { file: 'Swordsman_lvl1_attack_with_shadow.png',      frames: 8  },
      walkAtk: { file: 'Swordsman_lvl1_Walk_Attack_with_shadow.png', frames: 6  },
      runAtk:  { file: 'Swordsman_lvl1_Run_Attack_with_shadow.png',  frames: 8  },
      hurt:    { file: 'Swordsman_lvl1_Hurt_with_shadow.png',        frames: 5  },
      death:   { file: 'Swordsman_lvl1_Death_with_shadow.png',       frames: 7  },
    },
  },
  hero_lvl2: {
    basePath: 'assets/characters/swordsman/swordsman_level_2/',
    sheets: {
      idle:    { file: 'Swordsman_lvl2_Idle_with_shadow.png',        frames: 12 },
      walk:    { file: 'Swordsman_lvl2_Walk_with_shadow.png',        frames: 6  },
      run:     { file: 'Swordsman_lvl2_Run_with_shadow.png',         frames: 8  },
      attack:  { file: 'Swordsman_lvl2_attack_with_shadow.png',      frames: 8  },
      walkAtk: { file: 'Swordsman_lvl2_Walk_Attack_with_shadow.png', frames: 6  },
      runAtk:  { file: 'Swordsman_lvl2_Run_Attack_with_shadow.png',  frames: 8  },
      hurt:    { file: 'Swordsman_lvl2_Hurt_with_shadow.png',        frames: 5  },
      death:   { file: 'Swordsman_lvl2_Death_with_shadow.png',       frames: 7  },
    },
  },
  hero_lvl3: {
    basePath: 'assets/characters/swordsman/swordsman_level_3/',
    sheets: {
      idle:    { file: 'Swordsman_lvl3_Idle_with_shadow.png',        frames: 12 },
      walk:    { file: 'Swordsman_lvl3_Walk_with_shadow.png',        frames: 6  },
      run:     { file: 'Swordsman_lvl3_Run_with_shadow.png',         frames: 8  },
      attack:  { file: 'Swordsman_lvl3_attack_with_shadow.png',      frames: 8  },
      walkAtk: { file: 'Swordsman_lvl3_Walk_Attack_with_shadow.png', frames: 6  },
      runAtk:  { file: 'Swordsman_lvl3_Run_Attack_with_shadow.png',  frames: 8  },
      hurt:    { file: 'Swordsman_lvl3_Hurt_with_shadow.png',        frames: 5  },
      death:   { file: 'Swordsman_lvl3_Death_with_shadow.png',       frames: 7  },
    },
  },
};

for (let level = 4; level <= 9; level++) {
  const prefix = `lvl${level}`;
  HERO_ASSETS[`hero_lvl${level}`] = {
    basePath: `assets/characters/swordsman/swordsman_level_${level}/`,
    sheets: {
      idle:    { file: `${prefix}_Idle_with_shadow.png`,        frames: 12 },
      walk:    { file: `${prefix}_Walk_with_shadow.png`,        frames: 6  },
      run:     { file: `${prefix}_Run_with_shadow.png`,         frames: 8  },
      attack:  { file: `${prefix}_attack_with_shadow.png`,      frames: 7  },
      walkAtk: { file: `${prefix}_Walk_Attack_with_shadow.png`, frames: 6  },
      runAtk:  { file: `${prefix}_Run_Attack_with_shadow.png`,  frames: 8  },
      hurt:    { file: `${prefix}_Hurt_with_shadow.png`,        frames: 5  },
      death:   { file: `${prefix}_Death_with_shadow.png`,       frames: 7  },
    },
  };
}

const ITEM_DEFS = {
  pine_plank: {
    id: 'pine_plank',
    name: 'Pine Plank',
    iconKey: 'pine_plank_icon',
    craftFrom: [{ itemId: 'pine_wood', quantity: 2 }],
  },
  walnut_plank: {
    id: 'walnut_plank',
    name: 'Walnut Plank',
    iconKey: 'walnut_plank_icon',
    craftFrom: [{ itemId: 'walnut_wood', quantity: 2 }],
  },
  ancient_plank: {
    id: 'ancient_plank',
    name: 'Ancient Plank',
    iconKey: 'ancient_plank_icon',
    craftFrom: [{ itemId: 'ancient_wood', quantity: 2 }],
  },
  bronze_ingot: {
    id: 'bronze_ingot',
    name: 'Bronze Ingot',
    iconKey: 'bronze_ingot_icon',
    craftFrom: [{ itemId: 'bronze_ore', quantity: 2 }],
  },
  iron_ingot: {
    id: 'iron_ingot',
    name: 'Iron Ingot',
    iconKey: 'iron_ingot_icon',
    craftFrom: [{ itemId: 'iron_ore', quantity: 2 }],
  },
  gold_ingot: {
    id: 'gold_ingot',
    name: 'Gold Ingot',
    iconKey: 'gold_ingot_icon',
    craftFrom: [{ itemId: 'gold_ore', quantity: 2 }],
  },
};

const CRAFTING_RECIPES_DISABLED = {
  pine_plank: {
    id: 'pine_plank',
    enabled: false,
    output: { itemId: 'pine_plank', quantity: 1 },
    ingredients: [{ itemId: 'pine_wood', quantity: 2 }],
  },
  walnut_plank: {
    id: 'walnut_plank',
    enabled: false,
    output: { itemId: 'walnut_plank', quantity: 1 },
    ingredients: [{ itemId: 'walnut_wood', quantity: 2 }],
  },
  ancient_plank: {
    id: 'ancient_plank',
    enabled: false,
    output: { itemId: 'ancient_plank', quantity: 1 },
    ingredients: [{ itemId: 'ancient_wood', quantity: 2 }],
  },
  bronze_ingot: {
    id: 'bronze_ingot',
    enabled: false,
    output: { itemId: 'bronze_ingot', quantity: 1 },
    ingredients: [{ itemId: 'bronze_ore', quantity: 2 }],
  },
  iron_ingot: {
    id: 'iron_ingot',
    enabled: false,
    output: { itemId: 'iron_ingot', quantity: 1 },
    ingredients: [{ itemId: 'iron_ore', quantity: 2 }],
  },
  gold_ingot: {
    id: 'gold_ingot',
    enabled: false,
    output: { itemId: 'gold_ingot', quantity: 1 },
    ingredients: [{ itemId: 'gold_ore', quantity: 2 }],
  },
};

const CFG = {
  DEBUG_GRID,
  CONSUMABLES,
  ITEMS: ITEM_DEFS,
  CRAFTING: {
    RECIPES_DISABLED: CRAFTING_RECIPES_DISABLED,
  },

  // ── Map ──────────────────────────────────────────────────────────────────
  MAP_JSON : 'assets/world/2dmap.json?v=2',
  TILE_SIZE: 16,

  // ── All tilesets in the exact order they appear in 2dmap.json ───────────
  // The path values match the `image` field in the JSON (relative to assets/world/).
  // Collection tilesets (Dynamic_props) have no `image` and are skipped by _buildMeta.
  TILESETS: [
    // ── Original tilesets ────────────────────────────────────────────────
    /* 00 */ { key:'grass_base',           path:'assets/world/craftpix-net-189510-grassland-top-down-tileset-pixel-art/PNG/Grassland_Base_Ground.png' },
    /* 01 */ { key:'Flowing_water_3',      path:'assets/world/craftpix-net-189510-grassland-top-down-tileset-pixel-art/PNG/Grassland_water_detilazation_v2.png' },
    /* 02 */ { key:'dessert_beach',        path:'assets/world/craftpix-net-874337-desert-tileset-top-down-pixel-art/PNG/Desert_Ground_grass.png' },
    /* 03 */ { key:'grass_side_water',     path:'assets/world/craftpix-net-189510-grassland-top-down-tileset-pixel-art/PNG/Grassland_Water_coasts.png' },
    /* 04 */ { key:'farm_house',           path:'assets/world/craftpix-net-471853-top-down-farm-with-animals-pixel-art-asset-pack/PNG/Farm_Houses.png' },
    /* 05 */ { key:'vegetables',           path:'assets/world/craftpix-net-471853-top-down-farm-with-animals-pixel-art-asset-pack/PNG/Barn_interior.png' },
    /* 06 */ { key:'forest_and_bricks',    path:'assets/world/craftpix-net-189510-grassland-top-down-tileset-pixel-art/PNG/Grassland_Trees_rocks.png' },
    /* 07 */ { key:'trees_veggies',        path:'assets/world/craftpix-net-471853-top-down-farm-with-animals-pixel-art-asset-pack/PNG/Farm_Plants.png' },
    /* 08 */ { key:'Trees_rocks',          path:'assets/world/craftpix-net-189510-grassland-top-down-tileset-pixel-art/PNG/Grassland_Trees_rocks.png' },
    /* 09 */ { key:'Grassland_details',    path:'assets/world/craftpix-net-189510-grassland-top-down-tileset-pixel-art/PNG/Grassland_Details.png' },
    /* 10 */ { key:'dungeon_left_assets',  path:'assets/world/craftpix-net-874337-desert-tileset-top-down-pixel-art/PNG/Desert_Objects_animated.png' },
    /* 11 */ { key:'fruit_trees',          path:'assets/world/craftpix-net-471853-top-down-farm-with-animals-pixel-art-asset-pack/Tiled_files/Farm2_trees.png' },
    /* 12 */ { key:'fence_animation',      path:'assets/world/craftpix-net-471853-top-down-farm-with-animals-pixel-art-asset-pack/Tiled_files/Farm2_wicket_animation.png' },
    /* 13 */ { key:'Farm_Road',            path:'assets/world/craftpix-net-471853-top-down-farm-with-animals-pixel-art-asset-pack/Tiled_files/Farm2_Road.png' },
    /* 14 */ { key:'ground_grass_bricks',  path:'assets/world/craftpix-net-471853-top-down-farm-with-animals-pixel-art-asset-pack/Tiled_files/Farm2_ground_grass_bricks.png' },
    /* 15 */ { key:'Houses',               path:'assets/world/craftpix-net-471853-top-down-farm-with-animals-pixel-art-asset-pack/Tiled_files/Farm2_Houses.png' },
    /* 16 */ { key:'Chicken_animation',    path:'assets/world/craftpix-net-471853-top-down-farm-with-animals-pixel-art-asset-pack/Tiled_files/Farm2_Chicken_animation.png' },
    /* 17 */ { key:'veggies_Plants_farm',  path:'assets/world/craftpix-net-471853-top-down-farm-with-animals-pixel-art-asset-pack/Tiled_files/Farm2_Plants.png' },
    /* 18 */ { key:'Flowing_water_1',      path:'assets/world/craftpix-net-471853-top-down-farm-with-animals-pixel-art-asset-pack/Tiled_files/Farm2_water_detilazation.png' },
    /* 19 */ { key:'More_trees_green',     path:'assets/world/craftpix-net-471853-top-down-farm-with-animals-pixel-art-asset-pack/Tiled_files/Farm2_Objects_outside.png' },
    /* 20 */ { key:'fishes',               path:'assets/world/craftpix-net-471853-top-down-farm-with-animals-pixel-art-asset-pack/Tiled_files/Farm2_fishes.png' },
    /* 21 */ { key:'Cow_animation',        path:'assets/world/craftpix-net-471853-top-down-farm-with-animals-pixel-art-asset-pack/Tiled_files/Farm2_Cow_animation.png' },
    /* 22 */ { key:'Ground_grass_details', path:'assets/world/craftpix-net-471853-top-down-farm-with-animals-pixel-art-asset-pack/Tiled_files/Farm2_Ground_grass_details.png' },
    /* 23 */ { key:'house_windows',        path:'assets/world/craftpix-net-471853-top-down-farm-with-animals-pixel-art-asset-pack/Tiled_files/Farm2_house_windows.png' },
    /* 24 */ { key:'Doors',                path:'assets/world/craftpix-net-471853-top-down-farm-with-animals-pixel-art-asset-pack/Tiled_files/Farm2_Doors.png' },
    /* 25 */ { key:'bridge',               path:'assets/world/craftpix-net-189510-grassland-top-down-tileset-pixel-art/Tiled_files/Ground_Water_coasts.png' },
    /* 26 */ { key:'Ground_grass',         path:'assets/world/craftpix-net-189510-grassland-top-down-tileset-pixel-art/Tiled_files/ground_grasss.png' },
    /* 27 */ { key:'Right_dungeon',        path:'assets/world/craftpix-net-695666-free-undead-tileset-top-down-pixel-art/Tiled_files/undead_Objects_animated.png' },
    /* 28 */ { key:'dungeon_wall',         path:'assets/world/craftpix-net-688848-cave-tileset-top-down-pixel-art/Tiled_files/cave_Ground.png' },
    /* 29 */ { key:'mines_details',        path:'assets/world/craftpix-net-688848-cave-tileset-top-down-pixel-art/Tiled_files/cave_details.png' },
    /* 30 */ { key:'Crystals_rocks',       path:'assets/world/craftpix-net-688848-cave-tileset-top-down-pixel-art/Tiled_files/cave_Objects.png' },
    /* 31 */ { key:'dark_mine_spots',      path:'assets/world/craftpix-net-688848-cave-tileset-top-down-pixel-art/Tiled_files/cave_spots.png' },
    /* 32 */ { key:'dark_brown_coast',     path:'assets/world/craftpix-net-688848-cave-tileset-top-down-pixel-art/Tiled_files/cave_Water_coasts.png' },
    /* 33 */ { key:'volcano_yellow_small', path:'assets/world/craftpix-net-688848-cave-tileset-top-down-pixel-art/PNG/cave_bubbles_source.png' },
    /* 34 */ { key:'Lava',                 path:'assets/world/craftpix-net-688848-cave-tileset-top-down-pixel-art/Tiled_files/cave_Lava.png' },
    /* 35 */ { key:'Flowingg_water_4',     path:'assets/world/craftpix-net-189510-grassland-top-down-tileset-pixel-art/Tiled_files/Ground_water_detilazation_v2.png' },
    /* 36 */ { key:'road_Details',         path:'assets/world/craftpix-net-189510-grassland-top-down-tileset-pixel-art/Tiled_files/Ground_Details.png' },
    /* 37 */ { key:'Trees_rocks_v1',       path:'assets/world/craftpix-net-189510-grassland-top-down-tileset-pixel-art/Tiled_files/Ground_Trees_rocks.png' },
    /* 38 */ { key:'Flowing_water_2',      path:'assets/world/craftpix-net-189510-grassland-top-down-tileset-pixel-art/Tiled_files/Ground_water_detilazation.png' },
    /* 39 */ { key:'beach_coast_sand',     path:'assets/world/craftpix-net-874337-desert-tileset-top-down-pixel-art/Tiled_files/dessert_Water_coasts.png' },
    /* 40 */ { key:'lite_dessert_spots',   path:'assets/world/craftpix-net-874337-desert-tileset-top-down-pixel-art/Tiled_files/dessert_spots.png' },
    /* 41 */ { key:'Dessert_Objects',      path:'assets/world/craftpix-net-874337-desert-tileset-top-down-pixel-art/Tiled_files/dessert_Objects.png' },
    /* 42 */ { key:'sand_flowing',         path:'assets/world/craftpix-net-874337-desert-tileset-top-down-pixel-art/Tiled_files/dessert_sand.png' },
    /* 43 */ { key:'rocks_details',        path:'assets/world/craftpix-net-874337-desert-tileset-top-down-pixel-art/Tiled_files/dessert_rocks_details.png' },
    /* 44 */ { key:'dessert_grass_path',   path:'assets/world/craftpix-net-874337-desert-tileset-top-down-pixel-art/Tiled_files/dessert_Ground_grass.png' },
    /* 45 */ { key:'Dessert_Details',      path:'assets/world/craftpix-net-874337-desert-tileset-top-down-pixel-art/Tiled_files/dessert_Details.png' },

    // ── cave_Objects appears at two firstgids (same image — load once, key both) ─
    /* 46 */ { key:'cave_objects_b',       path:'assets/world/craftpix-net-688848-cave-tileset-top-down-pixel-art/Tiled_files/cave_Objects.png' },

    // ── Top-extension tilesets ─────────────────────────────────────────────
    /* 47 */ { key:'objects_animated_top',    path:'assets/world/craftpix-net-688848-cave-tileset-top-down-pixel-art/Tiled_files/cave_Objects_animated.png'  },
    /* 48 */ { key:'water_coasts_top',        path:'assets/world/craftpix-net-688848-cave-tileset-top-down-pixel-art/Tiled_files/cave_Water_coasts.png'      },
    /* 49 */ { key:'crystals_rocks_top',      path:'assets/world/craftpix-net-688848-cave-tileset-top-down-pixel-art/Tiled_files/cave_Objects.png'           },
    /* 50 */ { key:'lava_top',                path:'assets/world/craftpix-net-688848-cave-tileset-top-down-pixel-art/Tiled_files/cave_Lava.png'              },
    /* 51 */ { key:'bubbles_top',             path:'assets/world/craftpix-net-688848-cave-tileset-top-down-pixel-art/Tiled_files/cave_bubbles.png'           },
    /* 52 */ { key:'details_top',             path:'assets/world/craftpix-net-688848-cave-tileset-top-down-pixel-art/Tiled_files/cave_details.png'           },
    /* 53 */ { key:'ground_top',              path:'assets/world/craftpix-net-688848-cave-tileset-top-down-pixel-art/Tiled_files/cave_Ground.png'            },
    /* 54 */ { key:'objects_animated2_top',   path:'assets/world/craftpix-net-688848-cave-tileset-top-down-pixel-art/Tiled_files/cave_Objects_animated2.png' },
    /* 55 */ { key:'lava_detilazation_top',   path:'assets/world/craftpix-net-688848-cave-tileset-top-down-pixel-art/Tiled_files/cave_Lava_detilazation.png' },
    /* 56 */ { key:'spots_top',               path:'assets/world/craftpix-net-688848-cave-tileset-top-down-pixel-art/Tiled_files/cave_spots.png'             },
    /* 57 */ { key:'water_detilazation2_top', path:'assets/world/craftpix-net-688848-cave-tileset-top-down-pixel-art/Tiled_files/cave_water_detilazation_v2.png' },

    // ── Left-extension tilesets ───────────────────────────────────────────
    /* 58 */ { key:'spots_left',              path:'assets/world/craftpix-net-874337-desert-tileset-top-down-pixel-art/Tiled_files/dessert_spots.png'            },
    /* 59 */ { key:'sand_left',               path:'assets/world/craftpix-net-874337-desert-tileset-top-down-pixel-art/Tiled_files/dessert_sand.png'             },
    /* 60 */ { key:'objects_left',            path:'assets/world/craftpix-net-874337-desert-tileset-top-down-pixel-art/Tiled_files/dessert_Objects.png'          },
    /* 61 */ { key:'rocks_details_left',      path:'assets/world/craftpix-net-874337-desert-tileset-top-down-pixel-art/Tiled_files/dessert_rocks_details.png'    },
    /* 62 */ { key:'animated_objects_left',   path:'assets/world/craftpix-net-874337-desert-tileset-top-down-pixel-art/Tiled_files/dessert_Animated_objects.png' },
    /* 63 */ { key:'ground_grass_left',       path:'assets/world/craftpix-net-874337-desert-tileset-top-down-pixel-art/Tiled_files/dessert_Ground_grass.png'     },
    /* 64 */ { key:'details_left',            path:'assets/world/craftpix-net-874337-desert-tileset-top-down-pixel-art/Tiled_files/dessert_Details.png'          },
    /* 65 */ { key:'water_detilazation_left', path:'assets/world/craftpix-net-874337-desert-tileset-top-down-pixel-art/Tiled_files/dessert_water_detilazation.png' },
    /* 66 */ { key:'water_coasts_left',       path:'assets/world/craftpix-net-874337-desert-tileset-top-down-pixel-art/Tiled_files/dessert_Water_coasts.png'     },
    /* 67 */ { key:'water_detilazation2_left',path:'assets/world/craftpix-net-874337-desert-tileset-top-down-pixel-art/Tiled_files/dessert_water_detilazation_v2.png' },

    // ── Right-extension tilesets (Skeleton Dungeon) ───────────────────────
    /* 68 */ { key:'water_detilazation_right',  path:'assets/world/craftpix-net-695666-free-undead-tileset-top-down-pixel-art/Tiled_files/undead_water_detilazation.png'  },
    /* 69 */ { key:'water_coasts_right',         path:'assets/world/craftpix-net-695666-free-undead-tileset-top-down-pixel-art/Tiled_files/undead_water_coasts.png'        },
    /* 70 */ { key:'objects_animated3_right',    path:'assets/world/craftpix-net-695666-free-undead-tileset-top-down-pixel-art/Tiled_files/undead_Objects_animated3.png'   },
    /* 71 */ { key:'ground_rocks_right',         path:'assets/world/craftpix-net-695666-free-undead-tileset-top-down-pixel-art/Tiled_files/undead_Ground_rocks.png'        },
    /* 72 */ { key:'objects_right',              path:'assets/world/craftpix-net-695666-free-undead-tileset-top-down-pixel-art/Tiled_files/undead_Objects.png'             },
    /* 73 */ { key:'objects_animated_right',     path:'assets/world/craftpix-net-695666-free-undead-tileset-top-down-pixel-art/Tiled_files/undead_Objects_animated.png'    },
    /* 74 */ { key:'details_right',              path:'assets/world/craftpix-net-695666-free-undead-tileset-top-down-pixel-art/Tiled_files/undead_details.png'             },
  ],

  // ── Player / Swordsman Lv1 ───────────────────────────────────────────────
  PLAYER: {
    SPEED        : 100,
    RUN_SPEED    : 160,
    START_X      : 1295,
    START_Y      : 1488,
    SPAWN        : { name:'PlayerSpawn', x:1295, y:1488 },
    SCALE        : 1.0,
    BODY_W       : 12,
    BODY_H       : 18,
    INTERACT_DIST: 72,
    MAX_HEALTH    : 100,
    MAX_STAMINA   : 100,
    STAMINA_DRAIN_PER_SEC: 35,
    STAMINA_REGEN_PER_SEC: 20,
    STAMINA_SPRINT_RESUME : 12,
    ATTACK_DAMAGE : 25,
    ATTACK_RANGE  : 42,
    ATTACK_ARC_W  : 44,
    ATTACK_ARC_H  : 38,
    ATTACK_COOLDOWN_MS : 550,
    ATTACK_HIT_DELAY_MS: 180,
    HURT_INVULN_MS     : 700,
    OFFSET_Y     : 28,
    FRAME_W      : 64,
    FRAME_H      : 64,
    BASE_PATH    : 'assets/characters/swordsman/swordsman_level_1/',
    START_LEVEL  : 1,
    HERO_LEVELS,
    HERO_STATS,
    HERO_ASSETS,
    XP_REWARDS   : ENEMY_XP_REWARDS,
    DEFAULT_XP_REWARD: 1,
    SHEETS: {
      idle    : { file:'Swordsman_lvl1_Idle_with_shadow.png',        frames:12 },
      walk    : { file:'Swordsman_lvl1_Walk_with_shadow.png',        frames:6  },
      run     : { file:'Swordsman_lvl1_Run_with_shadow.png',         frames:8  },
      attack  : { file:'Swordsman_lvl1_attack_with_shadow.png',      frames:8  },
      walkAtk : { file:'Swordsman_lvl1_Walk_Attack_with_shadow.png', frames:6  },
      runAtk  : { file:'Swordsman_lvl1_Run_Attack_with_shadow.png',  frames:8  },
      hurt    : { file:'Swordsman_lvl1_Hurt_with_shadow.png',        frames:5  },
      death   : { file:'Swordsman_lvl1_Death_with_shadow.png',       frames:7  },
    },
    DIRS: ['down','up','left','right'],
  },

  // ── Farming ──────────────────────────────────────────────────────────────
  FARMING: {
    STAGE_MS : 20_000,
    STAGES   : 4,
    YIELD    : 3,
    SOIL_SIZE: 32,
    SEEDS: {
      blue_berries: { name:'Blue Berries', color:0x4488FF },
      EggPlant:     { name:'Egg Plant',    color:0x8800AA },
      corn:         { name:'Corn',         color:0xFFDD00 },
      pumpkin:      { name:'Pumpkin',      color:0xFF6600 },
      red_berries:  { name:'Red Berries',  color:0xFF2244 },
      spinach:      { name:'Spinach',      color:0x22CC44 },
      tomato:       { name:'Tomato',       color:0xFF3300 },
      watermelon:   { name:'Watermelon',   color:0x33CC33 },
    },
  },

  // ── Trees ────────────────────────────────────────────────────────────────
  TREES: {
    CHOP_HITS  : 3,
    SCALE      : 2.2,
    RESPAWN_MS : 60_000,
    YIELD_WOOD : 3,
    AXES: {
      oak:    'oak_axe',
      pine:   'pine_axe',
      walnut: 'walnut_axe',
    },
  },

  // ── Mining ───────────────────────────────────────────────────────────────
  MINING: {
    RESPAWN_MS: 90_000,
    PICKAXES: {
      stone_pickaxe:  { tier:1, label:'Stone Pickaxe'  },
      bronze_pickaxe: { tier:2, label:'Bronze Pickaxe' },
      gold_pickaxe:   { tier:3, label:'Gold Pickaxe'   },
    },
  },

  ENEMIES: {
    ENABLED: true,
    RESPAWN_MS: 5 * 60 * 1000,
    SPAWNS: [
      { type: 'slime', tileX: 55, tileY: 111 },
      { type: 'slime', tileX: 37, tileY: 107 },
      { type: 'slime', tileX: 101, tileY: 112 },
      { type: 'goblin', tileX: 114, tileY: 92 },
      { type: 'goblin', tileX: 55, tileY: 77 },
      { type: 'goblin', tileX: 72, tileY: 50 },
      { type: 'golem', tileX: 117, tileY: 68 },
      { type: 'lizardman1', tileX: 25, tileY: 76 },
      { type: 'lizardman2', tileX: 26, tileY: 50 },
      { type: 'lizardman3', tileX: 18, tileY: 39 },
      { type: 'goblin', tileX: 23, tileY: 17 },
      { type: 'skeleton1', tileX: 153, tileY: 85 },
      { type: 'skeleton2', tileX: 170, tileY: 70 },
      { type: 'skeleton3', tileX: 155, tileY: 43 },
      { type: 'skeleton1', tileX: 170, tileY: 20 },
      { type: 'demon1', tileX: 105, tileY: 29 },
      { type: 'demon2', tileX: 66, tileY: 27 },
      { type: 'demon3', tileX: 59, tileY: 11 },
      { type: 'demon1', tileX: 104, tileY: 14 },
      { type: 'demon2', tileX: 127, tileY: 28 },
    ],
    STATS: ENEMY_STATS,
    TYPES: {
      slime: {
        ...ENEMY_STATS.slime,
        wanderSpeed: 16,
        visionRange: ENEMY_STATS.slime.detectionRange,
        attackCooldownMs: ENEMY_STATS.slime.attackCooldown,
        attackHitDelayMs: 260,
        wanderRadius: 42,
        bodyW: 18,
        bodyH: 14,
        bodyOffsetX: 23,
        bodyOffsetY: 38,
        scale: 1.0,
      },
      goblin: {
        ...ENEMY_STATS.goblin,
        wanderSpeed: 20,
        visionRange: ENEMY_STATS.goblin.detectionRange,
        attackCooldownMs: ENEMY_STATS.goblin.attackCooldown,
        attackHitDelayMs: 220,
        wanderRadius: 48,
        bodyW: 18,
        bodyH: 18,
        bodyOffsetX: 23,
        bodyOffsetY: 39,
        scale: 1.0,
      },
      lizardman1: {
        ...ENEMY_STATS.lizardman1,
        wanderSpeed: 19,
        visionRange: ENEMY_STATS.lizardman1.detectionRange,
        attackCooldownMs: ENEMY_STATS.lizardman1.attackCooldown,
        attackHitDelayMs: 230,
        wanderRadius: 46,
        bodyW: 18,
        bodyH: 18,
        bodyOffsetX: 23,
        bodyOffsetY: 39,
        scale: 1.0,
      },
      lizardman2: {
        ...ENEMY_STATS.lizardman2,
        wanderSpeed: 22,
        visionRange: ENEMY_STATS.lizardman2.detectionRange,
        attackCooldownMs: ENEMY_STATS.lizardman2.attackCooldown,
        attackHitDelayMs: 220,
        wanderRadius: 50,
        bodyW: 18,
        bodyH: 18,
        bodyOffsetX: 23,
        bodyOffsetY: 39,
        scale: 1.0,
      },
      lizardman3: {
        ...ENEMY_STATS.lizardman3,
        wanderSpeed: 20,
        visionRange: ENEMY_STATS.lizardman3.detectionRange,
        attackCooldownMs: ENEMY_STATS.lizardman3.attackCooldown,
        attackHitDelayMs: 220,
        wanderRadius: 52,
        bodyW: 18,
        bodyH: 18,
        bodyOffsetX: 23,
        bodyOffsetY: 39,
        scale: 1.0,
      },
      skeleton1: {
        ...ENEMY_STATS.skeleton1,
        wanderSpeed: 20,
        visionRange: ENEMY_STATS.skeleton1.detectionRange,
        attackCooldownMs: ENEMY_STATS.skeleton1.attackCooldown,
        attackHitDelayMs: 230,
        wanderRadius: 48,
        bodyW: 14,
        bodyH: 14,
        bodyOffsetX: 25,
        bodyOffsetY: 25,
        scale: 1.0,
      },
      skeleton2: {
        ...ENEMY_STATS.skeleton2,
        wanderSpeed: 23,
        visionRange: ENEMY_STATS.skeleton2.detectionRange,
        attackCooldownMs: ENEMY_STATS.skeleton2.attackCooldown,
        attackHitDelayMs: 220,
        wanderRadius: 50,
        bodyW: 14,
        bodyH: 14,
        bodyOffsetX: 25,
        bodyOffsetY: 25,
        scale: 1.0,
      },
      skeleton3: {
        ...ENEMY_STATS.skeleton3,
        wanderSpeed: 21,
        visionRange: ENEMY_STATS.skeleton3.detectionRange,
        attackCooldownMs: ENEMY_STATS.skeleton3.attackCooldown,
        attackHitDelayMs: 220,
        wanderRadius: 52,
        bodyW: 14,
        bodyH: 14,
        bodyOffsetX: 25,
        bodyOffsetY: 25,
        scale: 1.0,
      },
      demon1: {
        ...ENEMY_STATS.demon1,
        wanderSpeed: 20,
        visionRange: ENEMY_STATS.demon1.detectionRange,
        attackCooldownMs: ENEMY_STATS.demon1.attackCooldown,
        attackHitDelayMs: 240,
        wanderRadius: 50,
        bodyW: 24,
        bodyH: 20,
        bodyOffsetX: 52,
        bodyOffsetY: 78,
        scale: 0.8,
      },
      demon2: {
        ...ENEMY_STATS.demon2,
        wanderSpeed: 23,
        visionRange: ENEMY_STATS.demon2.detectionRange,
        attackCooldownMs: ENEMY_STATS.demon2.attackCooldown,
        attackHitDelayMs: 230,
        wanderRadius: 54,
        bodyW: 24,
        bodyH: 20,
        bodyOffsetX: 52,
        bodyOffsetY: 78,
        scale: 0.8,
      },
      demon3: {
        ...ENEMY_STATS.demon3,
        wanderSpeed: 21,
        visionRange: ENEMY_STATS.demon3.detectionRange,
        attackCooldownMs: ENEMY_STATS.demon3.attackCooldown,
        attackHitDelayMs: 230,
        wanderRadius: 56,
        bodyW: 24,
        bodyH: 20,
        bodyOffsetX: 52,
        bodyOffsetY: 78,
        scale: 0.8,
      },
      golem: {
        ...ENEMY_STATS.golem,
        wanderSpeed: 10,
        visionRange: ENEMY_STATS.golem.detectionRange,
        attackCooldownMs: ENEMY_STATS.golem.attackCooldown,
        attackHitDelayMs: 330,
        wanderRadius: 34,
        bodyW: 30,
        bodyH: 24,
        bodyOffsetX: 49,
        bodyOffsetY: 78,
        scale: 1.2,
      },
    },
    ASSETS: {
      slime: {
        frameW: 64,
        frameH: 64,
        basePath: 'assets/characters/slime/slime1/',
        sheets: {
          idle  : { file: 'Slime1_Idle_with_shadow.png',   frames: 6  },
          walk  : { file: 'Slime1_Walk_with_shadow.png',   frames: 8  },
          run   : { file: 'Slime1_Run_with_shadow.png',    frames: 8  },
          attack: { file: 'Slime1_Attack_with_shadow.png', frames: 10 },
          hurt  : { file: 'Slime1_Hurt_with_shadow.png',   frames: 5  },
          death : { file: 'Slime1_Death_with_shadow.png',  frames: 10 },
        },
      },
      goblin: {
        frameW: 64,
        frameH: 64,
        basePath: 'assets/characters/goblin/goblin1/',
        sheets: {
          idle  : { file: 'Idle0_with_shadow.png',   frames: 4 },
          walk  : { file: 'Walk0_with_shadow.png',   frames: 6 },
          run   : { file: 'Run0_with_shadow.png',    frames: 8 },
          attack: { file: 'Attack0_with_shadow.png', frames: 5 },
          hurt  : { file: 'Hurt0_with_shadow.png',   frames: 4 },
          death : { file: 'Death0_with_shadow.png',  frames: 6 },
        },
      },
      golem: {
        frameW: 128,
        frameH: 128,
        basePath: 'assets/characters/golem/golem1/',
        sheets: {
          idle  : { file: 'Golem1_Idle_with_shadow.png',   frames: 4 },
          walk  : { file: 'Golem1_Walk_with_shadow.png',   frames: 8 },
          run   : { file: 'Golem1_Run_with_shadow.png',    frames: 8 },
          attack: { file: 'Golem1_Attack_with_shadow.png', frames: 9 },
          hurt  : { file: 'Golem1_Hurt_with_shadow.png',   frames: 4 },
          death : { file: 'Golem1_Death_with_shadow.png',  frames: 8 },
        },
      },
      lizardman1: {
        frameW: 64,
        frameH: 64,
        basePath: 'assets/characters/lizardman1/lizardman1/',
        sheets: {
          idle  : { file: 'Lizardman1_Idle_with_shadow.png',   frames: 4 },
          walk  : { file: 'Lizardman1_Walk_with_shadow.png',   frames: 6 },
          run   : { file: 'Lizardman1_Run_with_shadow.png',    frames: 8 },
          attack: { file: 'Lizardman1_Attack_with_shadow.png', frames: 7 },
          hurt  : { file: 'Lizardman1_Hurt_with_shadow.png',   frames: 5 },
          death : { file: 'Lizardman1_Death_with_shadow.png',  frames: 7 },
        },
      },
      lizardman2: {
        frameW: 64,
        frameH: 64,
        basePath: 'assets/characters/lizardman2/lizardman2/',
        sheets: {
          idle  : { file: 'Lizardman2_Idle_with_shadow.png',   frames: 4 },
          walk  : { file: 'Lizardman2_Walk_with_shadow.png',   frames: 6 },
          run   : { file: 'Lizardman2_Run_with_shadow.png',    frames: 8 },
          attack: { file: 'Lizardman2_Attack_with_shadow.png', frames: 7 },
          hurt  : { file: 'Lizardman2_Hurt_with_shadow.png',   frames: 5 },
          death : { file: 'Lizardman2_Death_with_shadow.png',  frames: 7 },
        },
      },
      lizardman3: {
        frameW: 64,
        frameH: 64,
        basePath: 'assets/characters/lizardman3/lizardman3/',
        sheets: {
          idle  : { file: 'Lizardman3_Idle_with_shadow.png',   frames: 4 },
          walk  : { file: 'Lizardman3_Walk_with_shadow.png',   frames: 6 },
          run   : { file: 'Lizardman3_Run_with_shadow.png',    frames: 8 },
          attack: { file: 'Lizardman3_Attack_with_shadow.png', frames: 7 },
          hurt  : { file: 'Lizardman3_Hurt_with_shadow.png',   frames: 5 },
          death : { file: 'Lizardman3_Death_with_shadow.png',  frames: 7 },
        },
      },
      skeleton1: {
        frameW: 64,
        frameH: 64,
        basePath: 'assets/characters/skeleton1/skeleton1/',
        sheets: {
          idle  : { file: 'Skeleton1_Idle_with_shadow.png',   frames: 4 },
          walk  : { file: 'Skeleton1_Walk_with_shadow.png',   frames: 6 },
          run   : { file: 'Skeleton1_Run_with_shadow.png',    frames: 8 },
          attack: { file: 'Skeleton1_Attack_with_shadow.png', frames: 9 },
          hurt  : { file: 'Skeleton1_Hurt_with_shadow.png',   frames: 4 },
          death : { file: 'Skeleton1_Death_with_shadow.png',  frames: 6 },
        },
      },
      skeleton2: {
        frameW: 64,
        frameH: 64,
        basePath: 'assets/characters/skeleton2/skeleton2/',
        sheets: {
          idle  : { file: 'Skeleton2_Idle_with_shadow.png',   frames: 4 },
          walk  : { file: 'Skeleton2_Walk_with_shadow.png',   frames: 6 },
          run   : { file: 'Skeleton2_Run_with_shadow.png',    frames: 8 },
          attack: { file: 'Skeleton2_Attack_with_shadow.png', frames: 9 },
          hurt  : { file: 'Skeleton2_Hurt_with_shadow.png',   frames: 4 },
          death : { file: 'Skeleton2_Death_with_shadow.png',  frames: 6 },
        },
      },
      skeleton3: {
        frameW: 64,
        frameH: 64,
        basePath: 'assets/characters/skeleton3/skeleton3/',
        sheets: {
          idle  : { file: 'Skeleton3_Idle_with_shadow.png',   frames: 4 },
          walk  : { file: 'Skeleton3_Walk_with_shadow.png',   frames: 6 },
          run   : { file: 'Skeleton3_Run_with_shadow.png',    frames: 8 },
          attack: { file: 'Skeleton3_Attack_with_shadow.png', frames: 9 },
          hurt  : { file: 'Skeleton3_Hurt_with_shadow.png',   frames: 4 },
          death : { file: 'Skeleton3_Death_with_shadow.png',  frames: 6 },
        },
      },
      demon1: {
        frameW: 128,
        frameH: 128,
        basePath: 'assets/characters/demon1/demon1/',
        sheets: {
          idle  : { file: 'Demon1_Idle_with_shadow.png',   frames: 4  },
          walk  : { file: 'Demon1_Walk_with_shadow.png',   frames: 6  },
          run   : { file: 'Demon1_Run_with_shadow.png',    frames: 8  },
          attack: { file: 'Demon1_Attack_with_shadow.png', frames: 10 },
          hurt  : { file: 'Demon1_Hurt_with_shadow.png',   frames: 4  },
          death : { file: 'Demon1_Death_with_shadow.png',  frames: 13 },
        },
      },
      demon2: {
        frameW: 128,
        frameH: 128,
        basePath: 'assets/characters/demon2/demon2/',
        sheets: {
          idle  : { file: 'Demon2_Idle_with_shadow.png',   frames: 4  },
          walk  : { file: 'Demon2_Walk_with_shadow.png',   frames: 6  },
          run   : { file: 'Demon2_Run_with_shadow.png',    frames: 8  },
          attack: { file: 'Demon2_Attack_with_shadow.png', frames: 10 },
          hurt  : { file: 'Demon2_Hurt_with_shadow.png',   frames: 4  },
          death : { file: 'Demon2_Death_with_shadow.png',  frames: 13 },
        },
      },
      demon3: {
        frameW: 128,
        frameH: 128,
        basePath: 'assets/characters/demon3/demon3/',
        sheets: {
          idle  : { file: 'Demon3_Idle_with_shadow.png',   frames: 4  },
          walk  : { file: 'Demon3_Walk_with_shadow.png',   frames: 6  },
          run   : { file: 'Demon3_Run_with_shadow.png',    frames: 8  },
          attack: { file: 'Demon3_Attack_with_shadow.png', frames: 10 },
          hurt  : { file: 'Demon3_Hurt_with_shadow.png',   frames: 4  },
          death : { file: 'Demon3_Death_with_shadow.png',  frames: 13 },
        },
      },
    },
  },

  // ── Inventory ────────────────────────────────────────────────────────────
  INVENTORY: {
    COLS:5, ROWS:4, SLOT_SIZE:48, GAP:6,
  },

  // ── Hotkeys ──────────────────────────────────────────────────────────────
  KEY_INTERACT : 'F',
  KEY_INVENTORY: 'TAB',
  KEY_RUN      : 'SHIFT',
};
